"""rename username to display_name add user_type

Revision ID: 1949381f4166
Revises: ebad29d22634
Create Date: 2026-04-08 20:17:50.865016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1949381f4166'
down_revision = 'ebad29d22634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Add display_name with a server_default so existing rows get a value
        batch_op.add_column(sa.Column('display_name', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('user_type', sa.String(length=30), nullable=True))

    # Copy username → display_name for existing rows
    op.execute("UPDATE users SET display_name = username WHERE display_name IS NULL")

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('display_name', nullable=False)
        batch_op.drop_constraint(batch_op.f('users_username_key'), type_='unique')
        batch_op.create_unique_constraint('uq_users_display_name', ['display_name'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('users_username_key'), ['username'])
        batch_op.drop_column('user_type')
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
