"""add otp fields to user

Revision ID: 20d87dcc3ce2
Revises: f423c35e5f2a
Create Date: 2026-04-09 01:45:42.310783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d87dcc3ce2'
down_revision = 'f423c35e5f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_email_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_email_verified')
        batch_op.drop_column('otp_expires_at')
        batch_op.drop_column('otp_code')

    # ### end Alembic commands ###
