"""add db indexes

Revision ID: f423c35e5f2a
Revises: 1949381f4166
Create Date: 2026-04-08 20:56:19.757598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f423c35e5f2a'
down_revision = '1949381f4166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.create_index('ix_pm_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_pm_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('ix_tasks_assigned_to', ['assigned_to'], unique=False)
        batch_op.create_index('ix_tasks_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_tasks_project_status', ['project_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_project_status')
        batch_op.drop_index('ix_tasks_project_id')
        batch_op.drop_index('ix_tasks_assigned_to')

    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_index('ix_pm_user_id')
        batch_op.drop_index('ix_pm_project_id')

    # ### end Alembic commands ###
